services:
  dex-web:
    image: image_name_placeholder:latest
    container_name: dex-web
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped

networks:
  default:
    external: true
    name: network1